"""Code Automatically Generated By: @em-mw
Dip Coating Machine Programmer"""

import time, busio, digitalio, board
import KeyPad
import os



def main(step_pin_dip, dir_pin_dip, step_pin_rot, dir_pin_rot):
    while True:
        dir_pin_dip.value = False
        for _ in range(600):
            step_pin_dip.value = True
            time.sleep(0.0022727272727272726)
            step_pin_dip.value = False

        if KeyPad.getkey() == 14:
            
            break

        for _ in range(0):
            dir_pin_dip.value = False
            for _ in range(200):
                step_pin_rot.value = True
                time.sleep(0.001)
                step_pin_rot.value = False

        if KeyPad.getkey() == 14:
            break
